In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("training_set.csv")

In [3]:
x =df.drop(columns = ["Unnamed: 0", "Y"])

In [4]:
y = df["Y"]

In [5]:
# spliting dataset
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [7]:
X_train = sc.fit_transform(X_train)

In [8]:
X_test = sc.transform(X_test)

In [10]:
import tensorflow

In [11]:
tensorflow.__version__

'2.8.0'

In [13]:
X_train.shape, X_test.shape

((3128, 57), (782, 57))

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [24]:
model = Sequential()

In [17]:
X_train.shape[1]

57

In [25]:
model.add(Dense(12, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [26]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
r = model.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
98/98 [==============================] - 4s 7ms/step - loss: 0.6181 - accuracy: 0.6889
Epoch 2/100
98/98 [==============================] - 1s 6ms/step - loss: 0.4112 - accuracy: 0.8545
Epoch 3/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2942 - accuracy: 0.9038
Epoch 4/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2409 - accuracy: 0.9178
Epoch 5/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2138 - accuracy: 0.9249
Epoch 6/100
98/98 [==============================] - 1s 6ms/step - loss: 0.1974 - accuracy: 0.9300
Epoch 7/100
98/98 [==============================] - 1s 6ms/step - loss: 0.1861 - accuracy: 0.9332
Epoch 8/100
98/98 [==============================] - 1s 6ms/step - loss: 0.1772 - accuracy: 0.9329
Epoch 9/100
98/98 [==============================] - 1s 6ms/step - loss: 0.1698 - accuracy: 0.9335
Epoch 10/100
98/98 [==============================] - 1s 6ms/step - loss: 0.1638 - accuracy: 0.9367
Epoch 11/

In [55]:
#model.save("final_model.h5")

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred = (y_pred > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
confusion_matrix(y_test, y_pred)

array([[428,  29],
       [ 20, 305]], dtype=int64)

In [ ]:
accuracy_score(y_test, y_pred)

0.9373401534526854

Model has high variance

In [42]:
# creating new model with drop out
model = Sequential()


In [43]:
#adding dropout
model.add(Dense(12, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(8, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

In [46]:
model.compile(metrics=['accuracy'], loss='binary_crossentropy', optimizer='adam')

In [47]:
r = model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
98/98 [==============================] - 3s 6ms/step - loss: 0.5807 - accuracy: 0.7120
Epoch 2/100
98/98 [==============================] - 1s 6ms/step - loss: 0.4509 - accuracy: 0.8210
Epoch 3/100
98/98 [==============================] - 1s 6ms/step - loss: 0.3705 - accuracy: 0.8648
Epoch 4/100
98/98 [==============================] - 1s 6ms/step - loss: 0.3300 - accuracy: 0.8782
Epoch 5/100
98/98 [==============================] - 1s 6ms/step - loss: 0.3082 - accuracy: 0.8894
Epoch 6/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2743 - accuracy: 0.9012
Epoch 7/100
98/98 [==============================] - 1s 5ms/step - loss: 0.2746 - accuracy: 0.9028
Epoch 8/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2468 - accuracy: 0.9098
Epoch 9/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2331 - accuracy: 0.9169
Epoch 10/100
98/98 [==============================] - 1s 6ms/step - loss: 0.2254 - accuracy: 0.9182
Epoch 11/

In [48]:
y_pred = model.predict(X_test)

In [51]:
y_pred = (y_pred > 0.5)

In [52]:
#y_pred

array([[False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [

In [53]:
confusion_matrix(y_test, y_pred)

array([[428,  29],
       [ 16, 309]], dtype=int64)

In [54]:
accuracy_score(y_test, y_pred)

0.9424552429667519

In [56]:
model.save("final_model.h5")

# Predicting test data

In [57]:
# predicting test data
test = pd.read_csv("test_set.csv")

In [58]:
test.head()

Unnamed: 0    X1   X2    X3   X4    X5    X6    X7    X8    X9  ...  X48  \
0           0  0.70  0.0  0.70  0.0  0.00  0.00  0.00  0.00  0.00  ...  0.0   
1           1  0.00  0.0  0.84  0.0  0.84  0.00  0.84  0.00  0.00  ...  0.0   
2           2  0.46  0.3  0.46  0.0  0.05  0.12  0.05  0.28  0.43  ...  0.0   
3           3  0.10  0.2  1.01  0.0  0.80  0.80  0.50  0.00  0.80  ...  0.0   
4           4  0.00  0.0  0.72  0.0  0.72  0.00  0.72  0.00  0.00  ...  0.0   

   X49    X50  X51    X52    X53    X54     X55  X56   X57  
0  0.0  0.000  0.0  0.105  0.000  0.000   2.342   47    89  
1  0.0  0.388  0.0  0.776  0.129  0.000  10.375  168   249  
2  0.0  0.065  0.0  0.325  0.756  0.153   5.891  193  3040  
3  0.0  0.110  0.0  0.490  0.158  0.015   8.550  669  1351  
4  0.0  0.364  0.0  0.729  0.121  0.000   7.781   32   249  

[5 rows x 58 columns]

In [59]:
x = test.drop(labels="Unnamed: 0", axis=1)

In [61]:
x.shape

(691, 57)

In [64]:
x = sc.transform(x)

In [65]:
y_pred_test = model.predict(x)

In [68]:
y_pred_test = (y_pred_test > 0.5)

In [69]:
y_pred_test

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [

In [80]:
y_pred_int = y_pred_test.astype("int")

In [81]:
test["y_pred"] = y_pred_int

In [82]:
test.shape

(691, 59)

In [83]:
test.head()

Unnamed: 0    X1   X2    X3   X4    X5    X6    X7    X8    X9  ...  X49  \
0           0  0.70  0.0  0.70  0.0  0.00  0.00  0.00  0.00  0.00  ...  0.0   
1           1  0.00  0.0  0.84  0.0  0.84  0.00  0.84  0.00  0.00  ...  0.0   
2           2  0.46  0.3  0.46  0.0  0.05  0.12  0.05  0.28  0.43  ...  0.0   
3           3  0.10  0.2  1.01  0.0  0.80  0.80  0.50  0.00  0.80  ...  0.0   
4           4  0.00  0.0  0.72  0.0  0.72  0.00  0.72  0.00  0.00  ...  0.0   

     X50  X51    X52    X53    X54     X55  X56   X57  y_pred  
0  0.000  0.0  0.105  0.000  0.000   2.342   47    89       0  
1  0.388  0.0  0.776  0.129  0.000  10.375  168   249       1  
2  0.065  0.0  0.325  0.756  0.153   5.891  193  3040       1  
3  0.110  0.0  0.490  0.158  0.015   8.550  669  1351       1  
4  0.364  0.0  0.729  0.121  0.000   7.781   32   249       1  

[5 rows x 59 columns]

In [84]:
test.to_csv("predicted_test_results.csv")